name = "sava-spin-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=sava-spin.com"
HMAC_KEY = "111f31382560e2c20a81f48676b17a913bf26b042f3175c44d92a25724904b0c"
COOKIE_NAME = "7sf"
PLAY_PATH = "try-now"
BUTTON_ID = "p83f8bbc449fc4128928ed63f4f4e8cda"
GATE_SALT = "6b62ee68b589faa5"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "5md6"
CTA_SELECTOR = ".play-button"
